# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Blog"
  weight = 20

[[main]]
  name = "Trip & Photo"
  parent = "Blog"
  pageRef = "blog"
  weight = 21

[[main]]
  name = "Tech"
  parent = "Blog"
  pageRef = "tech"
  weight = 22

[[main]]
  name = "Gallery"
  pageRef = "gallery"
  weight = 30

[[main]]
  name = "2023"
  parent = "Gallery"
  pageRef = "gallery/2023"
  weight = 302023

[[main]]
  name = "2024"
  parent = "Gallery"
  pageRef = "gallery/2024"
  weight = 302024

[[main]]
  name = "2025"
  parent = "Gallery"
  pageRef = "gallery/2025"
  weight = 302025

[[main]]
  name = "2026"
  parent = "Gallery"
  pageRef = "gallery/2026"
  weight = 302026

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 10

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 20
